// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AVChannelSetupStatusEnum.proto

#include "AVChannelSetupStatusEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace f1x {
namespace aasdk {
namespace proto {
namespace enums {
constexpr AVChannelSetupStatus::AVChannelSetupStatus(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct AVChannelSetupStatusDefaultTypeInternal {
  constexpr AVChannelSetupStatusDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AVChannelSetupStatusDefaultTypeInternal() {}
  union {
    AVChannelSetupStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AVChannelSetupStatusDefaultTypeInternal _AVChannelSetupStatus_default_instance_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_AVChannelSetupStatusEnum_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_AVChannelSetupStatusEnum_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_AVChannelSetupStatusEnum_2eproto = nullptr;

const uint32_t TableStruct_AVChannelSetupStatusEnum_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::f1x::aasdk::proto::enums::AVChannelSetupStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::f1x::aasdk::proto::enums::AVChannelSetupStatus)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::f1x::aasdk::proto::enums::_AVChannelSetupStatus_default_instance_),
};

const char descriptor_table_protodef_AVChannelSetupStatusEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036AVChannelSetupStatusEnum.proto\022\025f1x.aa"
  "sdk.proto.enums\":\n\024AVChannelSetupStatus\""
  "\"\n\004Enum\022\010\n\004NONE\020\000\022\010\n\004FAIL\020\001\022\006\n\002OK\020\002"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_AVChannelSetupStatusEnum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AVChannelSetupStatusEnum_2eproto = {
  false, false, 115, descriptor_table_protodef_AVChannelSetupStatusEnum_2eproto, "AVChannelSetupStatusEnum.proto", 
  &descriptor_table_AVChannelSetupStatusEnum_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_AVChannelSetupStatusEnum_2eproto::offsets,
  file_level_metadata_AVChannelSetupStatusEnum_2eproto, file_level_enum_descriptors_AVChannelSetupStatusEnum_2eproto, file_level_service_descriptors_AVChannelSetupStatusEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_AVChannelSetupStatusEnum_2eproto_getter() {
  return &descriptor_table_AVChannelSetupStatusEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_AVChannelSetupStatusEnum_2eproto(&descriptor_table_AVChannelSetupStatusEnum_2eproto);
namespace f1x {
namespace aasdk {
namespace proto {
namespace enums {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AVChannelSetupStatus_Enum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_AVChannelSetupStatusEnum_2eproto);
  return file_level_enum_descriptors_AVChannelSetupStatusEnum_2eproto[0];
}
bool AVChannelSetupStatus_Enum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr AVChannelSetupStatus_Enum AVChannelSetupStatus::NONE;
constexpr AVChannelSetupStatus_Enum AVChannelSetupStatus::FAIL;
constexpr AVChannelSetupStatus_Enum AVChannelSetupStatus::OK;
constexpr AVChannelSetupStatus_Enum AVChannelSetupStatus::Enum_MIN;
constexpr AVChannelSetupStatus_Enum AVChannelSetupStatus::Enum_MAX;
constexpr int AVChannelSetupStatus::Enum_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class AVChannelSetupStatus::_Internal {
 public:
};

AVChannelSetupStatus::AVChannelSetupStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:f1x.aasdk.proto.enums.AVChannelSetupStatus)
}
AVChannelSetupStatus::AVChannelSetupStatus(const AVChannelSetupStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:f1x.aasdk.proto.enums.AVChannelSetupStatus)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AVChannelSetupStatus::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AVChannelSetupStatus::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata AVChannelSetupStatus::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_AVChannelSetupStatusEnum_2eproto_getter, &descriptor_table_AVChannelSetupStatusEnum_2eproto_once,
      file_level_metadata_AVChannelSetupStatusEnum_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::f1x::aasdk::proto::enums::AVChannelSetupStatus* Arena::CreateMaybeMessage< ::f1x::aasdk::proto::enums::AVChannelSetupStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::f1x::aasdk::proto::enums::AVChannelSetupStatus >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
